version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    ports:
      - 27017:27017
  rabbitmq:
    image: rabbitmq:latest
  api:
    build:
      context: api
    ports:
      - 8080:8080
    depends_on:
      - 'mongodb'
      - 'rabbitmq'
    restart: on-failure
  posts:
    build:
      context: posts
    depends_on:
      - 'mongodb'
      - 'rabbitmq'
    restart: on-failure
  users:
    build:
      context: users
    depends_on:
      - 'mongodb'
    restart: on-failure
  redis:
    image: redis
    restart: on-failure
