version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    ports:
      - 27017:27017
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672:5672
  api:
    build:
      context: api
    ports:
      - 8080:8080
    depends_on:
      - 'mongodb'
      - 'rabbitmq'
    restart: on-failure
    # links: 
    #   'rabbitmq'
  posts:
    build:
      context: posts
    ports:
      - 4000:4000
    depends_on:
      - 'mongodb'
      - 'rabbitmq'
    restart: on-failure
  users:
    build:
      context: users
    ports:
      - 3000:3000
    depends_on:
      - 'mongodb'
    restart: on-failure
    # links: 
    #   'rabbitmq'